baseURL = "https://club-aquarium.de"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["taxonomy", "term", "robotsTXT"]

defaultContentLanguage = "de"

# The name of this wonderful theme ;-).
theme = "hugo-scroll"

# The "title" of your website
title = "Studentenclub Aquarium"

[params]
    # Button text to load actual external content (for GDPR reasons)
    map_button_text = "Externe Inhalte für Kartenansicht (osmand.net)"

    forms_baseurl = "https://cloud.club-aquarium.de/apps/forms/embed/"

    # A "copyright"-line to be added at the bottom of the page.
    # Hint: Markdown is supported in here as well. So you may e.g. add a link to your legal imprint-page.
    copyright = "**[Impressum](/imprint)** und **[Datenschutzerklärung](/gdpr)**  \n© Club Aquarium e. V."

    # The "description" of your website. This is used in the meta data of your generated html.
    description = "Studentenclub, Cocktailbar, Bühne und Veranstaltungsort"

    # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
    favicon = "images/favicon.png"

    # These "images" are used for the structured data templates. This will show up, when
    # services like Twitter or Slack want to generate a preview of a link to your site.
    # See https://gohugo.io/templates/internal#twitter-cards and
    # https://gohugo.io/templates/internal#open-graph.
    images = ["images/cover-image.jpg"]

    # Another "title" :-). This one is used as the site_name on the Hugo's internal
    # opengraph structured data template.
    # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
    title = "Club Aquarium - Bar, Bühne, Veranstaltungsort"

    hidedesignbyline = true

    partners_heading = "Unsere Partner"

    partners = [
        {url = "https://vdsc.de/", name = "Vereinigung Dresdner Studentenclubs (VDSC)", title = "Mitglied im VDSC", image = "/images/vdsc.svg"},
        {url = "https://www.studentenwerk-dresden.de/kultur/", name = "Studentenwerk Dresden", title = "Gefördert durch das Studentenwerk Dresden", image = "/images/studentenwerk.svg"}
    ]

    [params.meta]
        keywords = "studentenclub, bar, cocktails, dresden, events, party, drinks, bier, student"

[outputs]
    # the following is implicit, see https://gohugo.io/templates/output-formats/#default-output-formats
    # home = ["HTML", "RSS"]

    # create single event ICS files for each event
    page = ["HTML", "Calendar"]

    # create ICS for all events
    section = ["Calendar"]
